### ISSUE TITLE
Parche para eitb a la carta

### ISSUE THREAD

**Issue by erral** [tvalacarta/tvalacarta#1]
Hola:

He estado probando este plugin desde hace unas semanas y no me funcionaba de ninguna de las formas el plugin para eitb.

He estado mirando y probando el código, y con la ayuda de youtube-dl, he conseguido hacer funcionar eitb a la carta, y me gustaría contribuir de vuelta el código que he preparado.

Si pudieras subir el código aquí (parece que has creado el repositorio pero falta el 'push' final ;)), te hago un pull-request.

Saludos y gracias!

**Comment by tvalacarta** [comment]
Sí, voy a subir el código aquí en cuanto la versión esté lista.

Será genial si puedes subir esa corrección... yo he empezado a integrar también youtube-dl porque es muy cómodo para este plugin.

**Comment by erral** [comment]
Perfecto, espero entonces a que esté listo.
