### ISSUE TITLE
Telemundo

### ISSUE THREAD

**Issue by kchanto** [tvalacarta/tvalacarta#19]
Las listas de las series y los capítulos cargan bien, pero los videos no cargan. Sale un mensaje de algo como "las cosas pasan"... 
Gracias y saludos

**Comment by arieltools** [comment]
Esto parece relacionado con el error 404 encontrado al scraper intentar usar la pagina descargavideos.tv

P. ejemplo: 

http://www.descargavideos.tv/?web=http%3A%2F%2Fwww.telemundo.com%2Fnovelas%2F2016%2F10%2F27%2Fsilvana-sin-lana-
capitulo-69-poncho-le-cuenta-la-verdad-manuel

404

Sin embargo, al entrar la dirección directamente en la portada de la web, sí que encuentra los videos.

**Comment by arieltools** [comment]
Con el nuevo fichero, tengo el mismo error:

19:20:01 T:2626661184  NOTICE: tvalacarta.servers.telemundo get_video_url(page_url='http://www.telemundo.com/novelas/2016/10/27/silvana-sin-lana-capitulo-69-poncho-le-cuenta-la-v
erdad-manuel')
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools cachePage url=http://www.descargavideos.tv/?
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools MODO_CACHE=2 (no cachear)
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools downloadpage
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools url=http://www.descargavideos.tv/?
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools post=web=http%3A%2F%2Fwww.telemundo.com%2Fnovelas%2F2016%2F10%2F27%2Fsilvana-sin-lana-capitulo-69-poncho-le-cuenta-
la-verdad-manuel
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools ficherocookies=/home/[user]/.kodi/userdata/addon_data/plugin.video.tvalacarta/cookies.dat
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools Importando cookielib
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools cookielib disponible
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools cambio en politicas
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools Hay cookies
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools Leyendo fichero cookies
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools opener usando urllib2 (cookielib)
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools petición POST
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools ---------------------------
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools header User-Agent=Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; es-ES; rv:1.9.2.12) Gecko/20101026 Firefox/3.6.12
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools ---------------------------
19:20:01 T:2626661184  NOTICE: pelisalacarta.core.scrapertools Peticion con timeout
19:20:05 T:2816469824  NOTICE: Hole Umgebung
19:20:32 T:2626661184  NOTICE: Previous line repeats 5 times.
19:20:32 T:2626661184  NOTICE: Traceback (most recent call last):
                                              File "/home/[user]/.kodi/addons/plugin.video.tvalacarta/core/scrapertools.py", line 448, in downloadpage
                                                handle=urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 522: Origin Connection Time-out
19:20:32 T:2626661184  NOTICE: Traceback (most recent call last):
                                              File "/home/[user]/.kodi/addons/plugin.video.tvalacarta/platformcode/launcher.py", line 165, in run
                                                xbmctools.play_video(item)
                                              File "/home/[user]/.kodi/addons/plugin.video.tvalacarta/platformcode/xbmctools.py", line 107, in play_video
                                                alert_no_puedes_ver_video(item.server,url,motivo)
                                            NameError: global name 'url' is not defined
19:20:37 T:2816469824  NOTICE: Hole Umgebung
19:20:53 T:2509163328  NOTICE: Previous line repeats 2 times.
19:20:53 T:2509163328  NOTICE: ES: Client  from 192.168.0.13 timed out
19:20:53 T:2816469824  NOTICE: Hole Umgebung
