### ISSUE TITLE
No habre los canales en DIRECTO

### ISSUE THREAD

**Issue by freddy0310** [tvalacarta/tvalacarta#26]
No deja entrar a la parte de los canales directos en mitele, debajo el log de error en Kodi.

08:05:24.079 T:14552   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
08:05:24.290 T:10624   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/mitele.png
08:05:27.862 T:7992   ERROR: Previous line repeats 1 times.
08:05:27.862 T:7992  NOTICE: plugintools.find_single_match pattern=id="([^"]+)"
08:05:29.215 T:6912   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/mitele.png
08:05:30.412 T:12300  NOTICE: plugintools.find_single_match pattern=id="([^"]+)"
08:05:36.218 T:14552   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.tvalacarta/?eyJwbG90IjogIiIsICJ0aXRsZSI6ICJEaXJlY3RvIiwgImZhbmFydCI6ICJDOlxcVXNlcnNcXFN0b2NrXFxBcHBEYXRhXFxSb2FtaW5nXFxLb2RpXFxhZGRvbnNcXHBsdWdpbi52aWRlby50dmFsYWNhcnRhXFxmYW5hcnQuanBnIiwgImFjdGlvbiI6ICJsb2FkbGl2ZXMiLCAiZnVsbHRpdGxlIjogIkRpcmVjdG8iLCAidGh1bWJuYWlsIjogIiIsICJjaGFubmVsIjogIm1pdGVsZSJ9
08:05:36.219 T:14552   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tvalacarta/?eyJwbG90IjogIiIsICJ0aXRsZSI6ICJEaXJlY3RvIiwgImZhbmFydCI6ICJDOlxcVXNlcnNcXFN0b2NrXFxBcHBEYXRhXFxSb2FtaW5nXFxLb2RpXFxhZGRvbnNcXHBsdWdpbi52aWRlby50dmFsYWNhcnRhXFxmYW5hcnQuanBnIiwgImFjdGlvbiI6ICJsb2FkbGl2ZXMiLCAiZnVsbHRpdGxlIjogIkRpcmVjdG8iLCAidGh1bWJuYWlsIjogIiIsICJjaGFubmVsIjogIm1pdGVsZSJ9) failed
08:05:36.562 T:10348  NOTICE: plugintools.find_single_match pattern=id="([^"]+)"
08:05:36.762 T:3892   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/mitele.png

**Comment by tvalacarta** [comment]
Hecho
