### ISSUE TITLE
Algunos directos rotos

### ISSUE THREAD

**Issue by danifr** [tvalacarta/tvalacarta#29]
Buenas,

desde hace unos días, los directos de los canales de Mediaset (Cuatro y Telecinco) están rotos (los de Atresmedia llevan un tiempo sin funcionar también pero esa es otra historia)

Echando un vistazo en /var/lib/kodi/.kodi/temp.kodi.log me he encontrado lo siguiente:
```
20:37:22.769 T:1474282336   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
20:37:22.770 T:1474282336   ERROR: CCurlFile::Open failed with code 403 for http://cuatro-mediaset-esp-live.secure.footprint.net/mediaset/cuatro/stream1/streamPlaylist.m3u8
```
Y en el caso de Telecinco tres cuartos de lo mismo:
```
20:42:51.705 T:1662108512   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
20:42:51.705 T:1662108512   ERROR: CCurlFile::Open failed with code 403 for http://telecinco-mediaset-esp-live.secure.footprint.net/mediaset/telecinco/stream1/streamPlaylist.m3u8
```

Sé que esto es como jugar un poco al gato y el ratón con las televisions, pero mi pregunta es: hay algún archivo qué podamos tocar para poder arreglar nosotros mismos los canales?

He hecho algunos greps en el directorio del plugin pero no he encontrado nada. ¿De dónde pilla tvalacarta los enlaces a las emisiones en directo?
 
Gracias!!

**Comment by tvalacarta** [comment]
Las URL están en cada canal, dentro de la función "directos". 

En el caso de mitele:

tvalacarta/python/main-classic/channels/mitele.py

`def directos(item=None):
    logger.info("tvalacarta.channels.rtve directos")

    itemlist = []

    itemlist.append( Item(channel=__channel__, action="play", title="Telecinco", url="http://telecinco-mediaset-esp-live.secure.footprint.net/mediaset/telecinco/stream1/streamPlaylist.m3u8", thumbnail="http://media.tvalacarta.info/canales/128x128/telecinco.png", category="Nacionales", folder=False) )
    itemlist.append( Item(channel=__channel__, action="play", title="Cuatro", url="http://cuatro-mediaset-esp-live.secure.footprint.net/mediaset/cuatro/stream1/streamPlaylist.m3u8", thumbnail="http://media.tvalacarta.info/canales/128x128/cuatro.png", category="Nacionales", folder=False) )
    itemlist.append( Item(channel=__channel__, action="play", title="Divinity", url="https://mdslivehls-i.akamaihd.net/hls/live/571648/divinity/bitrate_4.m3u8", thumbnail="http://media.tvalacarta.info/canales/128x128/divinity.png", category="Nacionales", folder=False) )
    itemlist.append( Item(channel=__channel__, action="play", title="FDF", url="https://mdslivehls-i.akamaihd.net/hls/live/571650/fdf/bitrate_4.m3u8", thumbnail="http://media.tvalacarta.info/canales/128x128/fdf.png", category="Nacionales", folder=False) )

    return itemlist
`

La idea es que esto pueda ser dinámico, de forma que resuelva la URL en el momento de querer ver el directo, pero de momento está puesto a piñón.

En Euronews por ejemplo la URL cambia de vez en cuando, así que cualquier URL que pongas deja de funcionar a los pocos días.

**Comment by tvalacarta** [comment]
He mirado y ya no funcionan.

Además no podemos usarlos para tvalacarta, esos links son piratas (no hay duda porque incluso hay canales de pago).

**Comment by susobaco** [comment]
Hola, yo tengo una lista pe direcciones IPTV que voy actualizando asiduamente, por que, la verdad varían bastante. Si os sirve de ayuda:
https://gitlab.com/susobaco/iptv_spain
Salud!

**Comment by DjMoren** [comment]
Con el PR https://github.com/tvalacarta/tvalacarta/pull/47 aplicado sí funcionan. En ese caso, al mergear se podría cerrar esta issue.

**Comment by Tugatito19** [comment]
Y como es posible sacar enlaces m3u de cualquier canal de tv? Por ser más explícito. Canal Dazn F1
