### ISSUE TITLE
Antena3 Noticias no detecta los últimos capítulos

### ISSUE THREAD

**Issue by elreymon** [tvalacarta/tvalacarta#30]
Antena3 Noticias, dentro de Atresplayer, no detecta la temporada de junio. Solo la de mayo y anteriores.

**Comment by nosuko** [comment]
He conseguido con el apartado Network del Inspector del navegador, ver las llamadas a la API. Intentaré reescribir la parte de Atresmedia, pues no parece complicado, pero han cambiado un poco la disposición de algunas partes, por lo que intentaré adaptarlo. Hay muchos cambios, sobre todo en la forma de la paginación y las opciones de indexado, así que habrá bastante trabajo para tenerlo de nuevo activo, pero voy a intentar hacer algo esta semana.
@tvalacarta si te parece intento hacer algo y subo un pull request a ver qué os parece y si seguimos con ello o qué.

**Comment by tvalacarta** [comment]
Echa un vistazo al foro, ya hay algún avance en este sentido:

https://www.mimediacenter.info/foro/viewtopic.php?f=25&t=20600

No se si estarán usando lo mismo o no.

**Comment by nosuko** [comment]
Vale, voy a continuar en el foro.

**Comment by tvalacarta** [comment]
Perdona, estoy hasta arriba estos días. De hecho son casi las 4 de la mañana y aquí estoy ja ja ja

Hasta donde yo se, el proxy de Kodi debería ser usado por los add-ons sin más. Eso sí, creo que debe ser un proxy SOCKS (aunque no estoy 100% seguro). Igual por eso no lo está pillando.

También lo puedes forzar por código, en python poner un proxy es sencillo y al final scrapertools por debajo usa python estándar (urllib y cosas así).

https://stackoverflow.com/questions/3168171/how-can-i-open-a-website-with-urllib-via-proxy-in-python

El tema es qué proxy poner :(

Si pones un proxy público en tvalacarta lo usará todo el mundo, y acabará saturado. Y si lo pones como configuración la gente no sabrá que poner.

**Comment by nosuko** [comment]
Muchas gracias @tvalacarta!!! Jeje, ya veo, eso de hacer tarde a los que nos gusta programar y no tenemos mucho tiempo, pues ya se sabe, jeje! Aunque yo ando con -6 horas respecto a España :)

El proxy tengo que usarlo porque me encuentro fuera de España. Digamos que es mi problema concreto por este motivo, pero no tiene nada que ver con el desarrollo del plugin. Es decir, que para usar lo de atresmedia no hace falta proxy si estás en España. De hecho, con lo que he avanzado ya (y lo que he visto que ha hecho Workingdead en el foro), debería verse todo lo que no fuera de pago.

Como yo me encuentro fuera de España, me sale que, o está geobloqueado, o que es de pago. Es decir, se puede "navegar" por toda la api nueva (sin IP española), pero no llegar a la parte donde está el video. Solo se puede llegar desde una IP española y siempre que no sea contenido de pago. Una vez tienes la url del video, esa url no está geobloqueada, vamos que con una IP extranjera desde la que estoy, se la meto en un .m3u al kodi y funciona perfectamente sin proxy y sin nada. Por tanto, el "truco" del cifrado hmac que se hacía en la antigua api, me temo que no podrá hacerse ahora.

En resumen, que me interesa poder usar un proxy para poder probar mi desarrollo como lo vería la gente en España. El proxy socks5 que tengo con IP española lo configuro en firefox y me permite ver la web de atresplayer perfectamente (los videos, directos, etc). Pero si lo meto en la config general de Kodi no hace nada (??). No he encontrado mucha información sobre el tema, así que estaba por modificar el scrapertools.py para forzar el proxy y así continuar el desarrollo (obviamente solo para probar esto). Si lo consigo quizás pondría una opción de configuración en el plugin para poder añadir un proxy. Seguiré averiguando el tema con el enlace que me has pasado, muchas gracias! De hecho ese enlace ahora que lo miro ya lo había encontrado antes y es justo lo que iba a probar ahora :)

Sobre el tema del login y la autenticación, he visto lo que ha hecho Workingdead y me parece que habrán metido Oauth. En ese caso el tema se complica y habrá que currárselo más.

Bueno, voy a ver si avanzo un poco más y sigo comentando en el foro (ya me he registrado), mejor que aquí. A ver si conseguimos sacar algo en claro ahí, que hay más usuarios para que opinen, y subo un commit.

Muchas gracias por todo y un saludo "austral" ;-)

**Comment by elreymon** [comment]
Buenas. Muchas gracias a ambos por todo vuestro esfuerzo y dedicación. Gran trabajo.

**Comment by kampanita** [comment]
Así da gusto!!!!

**Comment by DjMoren** [comment]
Creo que este hilo se podría cerrar ya 😅
