### ISSUE TITLE
Petición de inclusión de nuevos canales

### ISSUE THREAD

**Issue by kampanita** [tvalacarta/tvalacarta#34]
Me gustaría que se incorporaran los canales de dplay.es ( Dmax, Dkiss ).
Echaré un ojo a ver si soy capaz de implementarlos yo, pero seguro que a uds. les será sencillo.

**Comment by kampanita** [comment]
Perdón, andaba con la versión 4.0.5 y veo que en la 4.0.7 ya estan.

**Comment by tvalacarta** [comment]
Está sin terminar, si quieres echarle un vistazo adelante.

**Comment by kampanita** [comment]
El caso es que me da error nada más intentar abrir el canal ya en la primera llamada al .py y no veo donde o por qué....
Esto oxidao.

Estaría bien incluirlos, así como los canales de playZ de Rtve ( yo lo he hecho incluyendo esto en el mainlist )
`
 itemlist.append( Item(channel=CHANNELNAME, title="PlayZ"             , action="canal" , thumbnail = "" , url="http://www.rtve.es/alacarta/tve/playz/", extra="playz"))`

**Comment by tvalacarta** [comment]
Ahí te lo he subido para que lo veas, pero no funcionan los vídeos.

https://github.com/tvalacarta/tvalacarta/commit/b962967b0336877070c0994e20fa1d02e4aa6218

Parece que youtube-dl no los reconoce como válidos :(

**Comment by kampanita** [comment]
Muchas gracias.
La verdad es que estoy un poco oxidao ya con esto ... No soy capaz de ver porque falla la entrada al mainlist de dplay.py

**Comment by tvalacarta** [comment]
dplay ya está funcionando en la última versión :)

Probablemente el problema fuera por usar mezcla de tabuladores y espacios, Kodi es sensible con eso y cuando no estás acostumbrado suele dar problemas
