### ISSUE TITLE
Fallo al cargar programa de Tele5 (Mitele)

### ISSUE THREAD

**Issue by elreymon** [tvalacarta/tvalacarta#36]
Por ejemplo da fallo al recuperar el stream del programa "en mi casa" de Bertín Osborne intenta recuperar el stream del que el servidor devolvió un error 403. Pongo ejemplo:
17:07:00.538 T:837280512   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
17:07:00.538 T:837280512   ERROR: CCurlFile::Open failed with code 403 for http://miteleooyala-a.akamaihd.net/JtOWdraDE6wUUFd9D1mJa7ojMbc3JvYX/DOcJ-FxaFrRg4gtDEwOjJjcTowODE7R4
17:07:01.138 T:837280512   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
17:07:01.138 T:837280512   ERROR: CCurlFile::Open failed with code 403 for http://miteleooyala-a.akamaihd.net/JtOWdraDE6wUUFd9D1mJa7ojMbc3JvYX/DOcJ-FxaFrRg4gtDEwOjJjcTowODE7R4
17:07:01.138 T:837280512   ERROR: Open - failed to open source <http://miteleooyala-a.akamaihd.net/JtOWdraDE6wUUFd9D1mJa7ojMbc3JvYX/DOcJ-FxaFrRg4gtDEwOjJjcTowODE7R4>
17:07:01.138 T:837280512   ERROR: CVideoPlayer::OpenInputStream - error opening [http://miteleooyala-a.akamaihd.net/JtOWdraDE6wUUFd9D1mJa7ojMbc3JvYX/DOcJ-FxaFrRg4gtDEwOjJjcTowODE7R4]

**Comment by DjMoren** [comment]
Con el PR https://github.com/tvalacarta/tvalacarta/pull/47 aplicado sí funciona, al menos los que he probado aleatoriamente. En ese caso, al mergear se podría cerrar esta issue.

**Comment by elreymon** [comment]
Muchas gracias por el gran trabajo. A ver si se mergea pronto.

**Comment by kampanita** [comment]
Cierto, muchas gracias por el esfuerzo!
Hice hace algun tiempo un servicio para kodi para mantener PelisALaCarta actualizado cogiendo los ficheros de git , se puede configurar para el master o alguna rama....
Ahora que de momento parece que las actualizaciones no se mantienen ... igual lo retoco y lo adapto para TVaLaCarta ...

**Comment by elreymon** [comment]
Pues no sería para nada mala opción, la verdad.

**Comment by DjMoren** [comment]
> Cierto, muchas gracias por el esfuerzo!
> Hice hace algun tiempo un servicio para kodi para mantener PelisALaCarta actualizado cogiendo los ficheros de git , se puede configurar para el master o alguna rama....
> Ahora que de momento parece que las actualizaciones no se mantienen ... igual lo retoco y lo adapto para TVaLaCarta ...

Si al autor original del plugin no le importa, creo que sería una buena opción ya que desacopla bastante el tema de releases/correcciones. Llevo pensándolo bastante tiempo.

Va a haber que hacer mucho curro de aquí a cuando salga la nueva versión de Kodi ya que [hay que migrar todo a Python 3](https://kodi.tv/article/kodi-19-python-3-goes-live) así que no te partas el pecho tampoco. Supongo que habrá que hacer muchos cambios, limpiar bastante el código, quitar cosas que no se usan apenas (o dejarlas para el final de la migración), incluir librerías que puedan ayudar como _requests_, establecer un CI mínimo, plantillas de desarrollo para que el código sea uniforme, bla, bla, bla...

**Comment by tvalacarta** [comment]
En cuanto a las actualizaciones, voy a poner el mismo sistema que tenía funcionando en pelisalacarta ya que permitía actualizar tanto canales como servidores y librerías (youtube-dl). He ido subiendo las correcciones en los canales y ahora estoy con eso.

En cuanto a lo de Python 3 ya lo tengo en mente, pero no cuento con que haya que hacer mucho cambio. He tenido que adaptar otros proyectos y como está todo bastante encapsulado la verdad es que se hace sin demasiado problema.
