### ISSUE TITLE
Algunos capítulos de Atresmedia no se abren

### ISSUE THREAD

**Issue by kampanita** [tvalacarta/tvalacarta#39]
Algunos enlaces de "Crímenes Imperfectos"
 -> todos los canales -> nacionales -> atresmedia -> programas -> crimenes imperfectos, 

 no se abren pese a que muestran el código de enlace como si quisiera abrirlos. Te muestra el menu de ver en directo, descargar, etc. Pulso a abrir, y no se abre. No dice nada tampoco de que se haya producido algun error.

Pasa con muchos de los capitulos, otros los abre bien. 

Y si, es cierto que no marca los vistos, pero eso supongo que no será sencillo de hacer.

**Comment by DjMoren** [comment]
No aparece _Crímenes Imperfectos_ en la sección _Programas_. ¿Me sabes decir dónde está?
