### ISSUE TITLE
Cambios en la web de Atresmedia

### ISSUE THREAD

**Issue by susobaco** [tvalacarta/tvalacarta#41]
Hola, creo que han habido cambios en la web de atresplayer, y eso creo que hace que no salgan bien, los programas, los ultimos capítulos, etc, etc.
Mala pinta tiene ésto.
Salud!

**Comment by kampanita** [comment]
Detectan el dispositivo desde el que se accede a la web. A la raspi la tienen "capada" ( supongo que al plugin al completo ) y solo te permiten acceder desde web o su app de atresplayer.

Supongo que cambiando la cabecera que se envía con la información del navegador se podrá solucionar, habría que mirarlo. Pero si, tiene mala pinta y más viendo que el desarrollo está muy parado.

**Comment by kampanita** [comment]
>  headers.append(["User-Agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:18.0) Gecko/20100101 Firefox/18.0"])

Supongo que hay que cambiar esta parte para que deje de detectar la web que estamos usando el plugin de tvalacarta.

**Comment by susobaco** [comment]
Ok, y no sabes que habría que poner, no?, es para ir haciendo pruebas.

**Comment by tvalacarta** [comment]
Ese es el user agent de un navegador, no creo que lo bloqueen porque es un Firefox normal y corriente :(

He echado un vistazo y parece que no es tanto un tema de bloqueo como que han cambiado el API, bastante han aguantado con la que tenían.

**Comment by kampanita** [comment]
O sea que habrá que scrapearla desde cero otra vez, y se podrá seguir "funcionando", supongo ¿?
Me está tentando montar raspbian para poder seguir usandolo aunque sea desde el navegador, más que nada para ver que rendimiento da, seguro que no muy bueno :(
¿ Habrá que cambiarla por un tvbox android ?
... uso mucho el plugin para a3player.

**Comment by kampanita** [comment]
Muchísimas gracias.
