### ISSUE TITLE
El canal dplay No Funciona, no sale nada, solo ..  ¿Podrias revisarlo?

### ISSUE THREAD

**Issue by aixos** [tvalacarta/tvalacarta#45]
He mirado, y no funciona nada solo salen .. carpeta vacía.
Es un canal muy bueno de documentales y te agradecería si le puedes echar un viztazo
muchas gracias

**Comment by DjMoren** [comment]
Hola, realmente está corregido en el código fuente del proyecto, lo que pasa es que no se han publicado nuevas versiones del plugin incluyendo los cambios realizados desde hace bastante tiempo. 

Teóricamente, para actualizar se comprueba la url http://descargas.tvalacarta.info/tvalacarta-version.xml y se compara contra la versión que tienes en el archivo _version.xml_ en tu local. Ahora mismo la última versión es la 4.1.2.

Por ahora, lo que puedes hacer es copiar directamente el código de este repositorio y sustituirlo por el que tienes en la carpeta de addons (el contenido de la carpeta main-classic es el importante).

**Comment by aixos** [comment]
Muchas gracias @DjMoren  por la info.
Ya funciona , he efectuado todos los pasos, lo cuelgo en mi github
saludos

**Comment by susobaco** [comment]
@aixos incluiste los cambios en a3play?
