### ISSUE TITLE
Fallo en TV3.

### ISSUE THREAD

**Issue by susobaco** [tvalacarta/tvalacarta#46]
Hola, parece que ha habido un cambio en la web, no salen los capítulos de los programas.
Salud!
[kodi.log.txt](https://github.com/tvalacarta/tvalacarta/files/4060493/kodi.log.txt)

**Comment by tvalacarta** [comment]
Arreglado!

https://github.com/tvalacarta/tvalacarta/commit/60ddda5d504c1ba61751c7c91e3d9d9135710fca
