### ISSUE TITLE
EITB a la carta no funciona

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/tvalacarta#5]
Pues eso, EITB alacarta no funciona. Primero se ve que usa un json antiguo, del cual se pueden cambiar las keys y ya avanza en el código. Pero finalmente el mecanismo de obtención del vídeo es diferente.

**Comment by dagavi** [comment]
Acabo de ver que hay un commit de hace 12 días para cambiar este tema. Sin embargo que da error porque no puede importar youtube_dl.

He instalado el addon youtube_dl (del repositorio oficial) pero me sigue fallando el import.

**Comment by Palatosino** [comment]
Acabo de ver que hay un commit de hace unos días que debería arreglar esto, cambiando tanto el channel como el server.

Sin embargo me da fallo de import youtube_dl.

He instalado youtube_dl desde el repositorio oficial de Kodi, pero me sigue fallando el import.

**Comment by erral** [comment]
En qué versión de Kodi tienes ese error? He probado el plugin con los cambios de Eitb en Kodi 15 y 16 y un amigo lo ha probado en Kodi 14 y nos va bien...

Ten en cuenta que hay que descargar desde aquí el código fuente del plugin y copiarlo en tu dispositivo hasta que haya una nueva release.

Si quieres aquí puedes encontrar las release que incluyen los cambios de Eitb que puedes copiar a tu dispositivo e instalar (Addons -> instalar desde archivo ZIP):

http://eibar.org/blogak/erral/tvalacarta/

Son los 6 más recientes los que incluyen los cambios de eitb y la descargar de youtube_dl.

**Comment by izendegi** [comment]
Con el cambio de @erral a mi inicialmente me funcionó en Kodi 14, aunque posteriormente me ha empezado a dar fallos intermitentes y ayer no conseguí que funcionase (no se si será que han hecho algún cambio en EITB :-S). No se si será de ayuda pero en el log veo lo siguiente:

`20:02:54 T:1399845952  NOTICE: [eitb.py] get_video_url(page_url='http://www.eitb.tv/es/video/berandu-baino-lehen-berandu-baino-lehen/5419/112877/berandu-baino-lehen-aiora-errenteria-eta-bernardo-atxaga/')
20:03:00 T:1399845952  NOTICE: [eitb.tv] 112877: Downloading video JSON
20:03:00 T:1399845952  NOTICE: .
20:03:01 T:1399845952  NOTICE: [eitb.tv] 112877: Downloading auth token
20:03:01 T:1399845952  NOTICE: .
20:03:02 T:1399845952  NOTICE: [eitb.tv] 112877: Downloading m3u8 information
20:03:02 T:1399845952  NOTICE: .
20:03:02 T:1399845952  NOTICE: [eitb.tv] 112877: Downloading f4m manifest
20:03:02 T:1399845952  NOTICE: .
20:03:03 T:1399845952  NOTICE: Traceback (most recent call last):
20:03:03 T:1399845952  NOTICE:   File "/storage/.kodi/addons/plugin.video.tvalacarta/servers/servertools.py", line 160, in resolve_video_urls_for_playing
20:03:03 T:1399845952  NOTICE:     video_urls = server_connector.get_video_url( page_url=url , video_password=video_password )
20:03:03 T:1399845952  NOTICE:   File "/storage/.kodi/addons/plugin.video.tvalacarta/servers/eitb.py", line 29, in get_video_url
20:03:03 T:1399845952  NOTICE:     result = ydl.extract_info(page_url, download=False)
20:03:03 T:1399845952  NOTICE:   File "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/YoutubeDL.py", line 665, in extract_info
20:03:03 T:1399845952  NOTICE:     ie_result = ie.extract(url)
20:03:03 T:1399845952  NOTICE:   File "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/common.py", line 291, in extract
20:03:03 T:1399845952  NOTICE:     return self._real_extract(url)
20:03:03 T:1399845952  NOTICE:   File "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/eitb.py", line 89, in _real_extract
20:03:03 T:1399845952  NOTICE:     'timestamp': parse_iso8601(media.get('BROADCST_DATE'), ' '),
20:03:03 T:1399845952  NOTICE:   File "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/utils.py", line 865, in parse_iso8601
20:03:03 T:1399845952  NOTICE:     dt = datetime.datetime.strptime(date_str, date_format) - timezone
20:03:03 T:1399845952  NOTICE: TypeError: attribute of type 'NoneType' is not callable`

**Comment by erral** [comment]
Ese error a mí me lo da en algunos programas.

Creo que es debido a que youtube_dl no consigue extraer el BROADCST_DATE
correctamente. Yo me inclinaría  a que es un error de EITB...



On Tue, Mar 8, 2016 at 10:50 AM, Iñigo Zendegi <notifications@github.com>
wrote:

> Con el cambio de @erral <https://github.com/erral> a mi inicialmente me
> funcionó en Kodi 14, aunque posteriormente me ha empezado a dar fallos
> intermitentes y ayer no conseguí que funcionase (no se si será que han
> hecho algún cambio en EITB :-S). No se si será de ayuda pero en el log veo
> lo siguiente:
>
> 20:02:54 T:1399845952 NOTICE: [eitb.py] get_video_url(page_url='
> http://www.eitb.tv/es/video/berandu-baino-lehen-berandu-baino-lehen/5419/112877/berandu-baino-lehen-aiora-errenteria-eta-bernardo-atxaga/
> ')
> 20:03:00 T:1399845952 NOTICE: [eitb.tv] 112877: Downloading video JSON
> 20:03:00 T:1399845952 NOTICE: .
> 20:03:01 T:1399845952 NOTICE: [eitb.tv] 112877: Downloading auth token
> 20:03:01 T:1399845952 NOTICE: .
> 20:03:02 T:1399845952 NOTICE: [eitb.tv] 112877: Downloading m3u8
> information
> 20:03:02 T:1399845952 NOTICE: .
> 20:03:02 T:1399845952 NOTICE: [eitb.tv] 112877: Downloading f4m manifest
> 20:03:02 T:1399845952 NOTICE: .
> 20:03:03 T:1399845952 NOTICE: Traceback (most recent call last):
> 20:03:03 T:1399845952 NOTICE: File
> "/storage/.kodi/addons/plugin.video.tvalacarta/servers/servertools.py",
> line 160, in resolve_video_urls_for_playing
> 20:03:03 T:1399845952 NOTICE: video_urls = server_connector.get_video_url(
> page_url=url , video_password=video_password )
> 20:03:03 T:1399845952 NOTICE: File
> "/storage/.kodi/addons/plugin.video.tvalacarta/servers/eitb.py", line 29,
> in get_video_url
> 20:03:03 T:1399845952 NOTICE: result = ydl.extract_info(page_url,
> download=False)
> 20:03:03 T:1399845952 NOTICE: File
> "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/YoutubeDL.py",
> line 665, in extract_info
> 20:03:03 T:1399845952 NOTICE: ie_result = ie.extract(url)
> 20:03:03 T:1399845952 NOTICE: File
> "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/common.py",
> line 291, in extract
> 20:03:03 T:1399845952 NOTICE: return self._real_extract(url)
> 20:03:03 T:1399845952 NOTICE: File
> "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/eitb.py",
> line 89, in _real_extract
> 20:03:03 T:1399845952 NOTICE: 'timestamp':
> parse_iso8601(media.get('BROADCST_DATE'), ' '),
> 20:03:03 T:1399845952 NOTICE: File
> "/storage/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/utils.py",
> line 865, in parse_iso8601
> 20:03:03 T:1399845952 NOTICE: dt = datetime.datetime.strptime(date_str,
> date_format) - timezone
> 20:03:03 T:1399845952 NOTICE: TypeError: attribute of type 'NoneType' is
> not callable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tvalacarta/tvalacarta/issues/5#issuecomment-193692771>
> .
>



-- 
Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80

**Comment by erral** [comment]
He estado mirando si el error podría estar en el propio youtube_dl, y he hecho un diff entre la versión actual de youtube_dl en Github y la de la adaptación para XBMC,  y no hay cambios relativos al BROADCST_DATE:

```diff
erral@lindari:~$ diff official-eitb.py xmbc-eitb.py 
68,69c68,71
<                     formats.extend(self._extract_m3u8_formats(
<                         '%s?hdnts=%s' % (hls_url, token), video_id, m3u8_id='hls', fatal=False))
---
>                     m3u8_formats = self._extract_m3u8_formats(
>                         '%s?hdnts=%s' % (hls_url, token), video_id, m3u8_id='hls', fatal=False)
>                     if m3u8_formats:
>                         formats.extend(m3u8_formats)
73c75
<             formats.extend(self._extract_f4m_formats(
---
>             f4m_formats = self._extract_f4m_formats(
75c77,79
<                 video_id, f4m_id='hds', fatal=False))
---
>                 video_id, f4m_id='hds', fatal=False)
>             if f4m_formats:
>                 formats.extend(f4m_formats)
```

He instalado a mano youtube_dl, y he extraido la información del vídeo que indica @izendegi y la información del BROADCST_DATE está ahí, así que creo que puede ser un error momentáneo de Eitb...

**Comment by tvalacarta** [comment]
Cerramos entonces?

**Comment by erral** [comment]
Yo creo que sí

On Thu, May 26, 2016 at 10:52 PM, tvalacarta <notifications@github.com>
wrote:

> Cerramos entonces?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tvalacarta/tvalacarta/issues/5#issuecomment-221991035>
>



-- 
Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80
